"""
Rule-switching Markov task. Each sequence is generated by a random sparse transition table.
Partway through, the table is replaced. A model that adapts its own weights should recover
faster after the switch than a frozen model, and the loss-by-position-since-switch curve makes
that directly measurable.
"""
import torch


class RuleSwitchMarkov:
    def __init__(self, vocab=32, seq_len=256, n_switches=1, sparsity=3, seed=0, device="cpu"):
        self.vocab = vocab
        self.seq_len = seq_len
        self.n_switches = n_switches
        self.sparsity = sparsity
        self.g = torch.Generator().manual_seed(seed)
        self.device = device

    def _table(self, batch):
        V, s = self.vocab, self.sparsity
        logits = torch.full((batch, V, V), -1e9)
        idx = torch.rand(batch, V, V, generator=self.g).argsort(-1)[..., :s]
        w = torch.rand(batch, V, s, generator=self.g) * 2.0
        logits.scatter_(-1, idx, w)
        return torch.softmax(logits, -1)

    def batch(self, batch, total_len=None, n_switches=None):
        """returns x (B, T), y (B, T), switch positions (B, n_switches)"""
        V = self.vocab
        T = (total_len or self.seq_len) + 1
        n_sw = self.n_switches if n_switches is None else n_switches
        return self._generate(batch, V, T, n_sw)

    def stream(self, batch, n_seq, switches_per_window=0.5):
        """
        n_seq consecutive windows from one long sequence, rules persisting across windows.
        Yields (x, y, switches) with switch positions given relative to the window start
        (negative means the switch happened in an earlier window).
        """
        T = self.seq_len
        n_sw = max(1, int(round(n_seq * switches_per_window)))
        x, y, sw = self.batch(batch, total_len=n_seq * T, n_switches=n_sw)
        for s in range(n_seq):
            yield x[:, s * T:(s + 1) * T], y[:, s * T:(s + 1) * T], sw - s * T

    def _generate(self, batch, V, T, n_switches):
        self.n_switches, saved = n_switches, self.n_switches
        n_seg = self.n_switches + 1
        # switch points evenly spaced with jitter, never in the first or last 32 tokens
        base = torch.linspace(0, T, n_seg + 1)[1:-1]
        jitter = (torch.rand(batch, self.n_switches, generator=self.g) - 0.5) * (T / n_seg) * 0.5
        switches = (base[None] + jitter).long().clamp(32, T - 32)
        tables = [self._table(batch) for _ in range(n_seg)]
        seq = torch.empty(batch, T, dtype=torch.long)
        seq[:, 0] = torch.randint(0, V, (batch,), generator=self.g)
        seg = torch.zeros(batch, dtype=torch.long)
        for t in range(1, T):
            seg = seg + (switches == t).any(-1).long()
            P = torch.stack([tables[k][b] for b, k in enumerate(seg.tolist())])
            probs = P[torch.arange(batch), seq[:, t - 1]]
            seq[:, t] = torch.multinomial(probs, 1, generator=self.g).squeeze(-1)
        self.n_switches = saved
        x, y = seq[:, :-1].to(self.device), seq[:, 1:].to(self.device)
        return x, y, switches.to(self.device)
